version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      SECRET_KEY: ${SECRET_KEY:-supersecretkey}
      DATABASE_URL: postgresql+asyncpg://user:password@db:5432/adv_db
    depends_on:
      - db
    volumes:
      - .:/app
    command: python main.py

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: adv_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

volumes:
  postgres_data: